### ISSUE TITLE
Calculating checksum

### ISSUE THREAD

**Issue by vcollerji** [globalcitizen/php-iso7064#4]
In calculating the checksum, the $modulus is used to limit the number of digits ($checksum = ($modulus - $p + 1) % $modulus;). I believe it should rather be 100 for MOD 97-10 (the only one I studied), or omitted.

If you look at https://usersite.datalab.eu/printclass.aspx?type=wiki&id=91772, the example for "Calculation with remainder equal 0" creates a checksum of '98' for '0600001234586'. I verified by other means and sources, and I believe that to be correct. The current algorithm comes up with '01', because of using mod 97 to limit the number of digits to 2.

**Comment by globalcitizen** [comment]
Sounds good. The current default implementation has a bug open against it so if you are implying there is an issue it's probably the same. Anyway, the current implementation seems to work most of the time. I need to write some more tests. There are two implementations included, perhaps one is bug free. I will try to find time to look at this over the next few weeks.

Pull requests accepted!

**Comment by globalcitizen** [comment]
Welcome to retry with new release. There was a bug discovered in one algorithm only.
